# Custom Language File for Launcher Customizer

[ejs.app]
title = "휴롱의 마인크래프트 서버"

[ejs.landing]
mediaGitHubURL = "https://github.com/GTYoon/hulonge"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaAfreecaTVURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/GTYoon/hulonge"
supportLink = "https://github.com/GTYoon/hulonge/issues"

[ejs.welcome]
welcomeHeader = "휴롱의 마인크래프트 서버"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."